// -----------------------------------------------------------------------------
// Testbench for sigmoid_subenv module (Q16.16 fixed-point)
//
// Exercises the three activation paths via the opcode selector.
// Uses ONE shared check_result task (same format as the stand-alone sigmoid TB).
// The opcode is set immediately before each `include, so every check_result
// call inside that file runs against the correct function:
//
//   opcode = 2'b00  ->  `include "sigmoid_vectors.sv"
//                       `include "sigmoid_neg_vectors.sv"
//   opcode = 2'b01  ->  `include "tanh_vectors.sv"
//   opcode = 2'b10  ->  `include "gelu_vectors.sv"
//
// Vector files are the existing ones generated by sigmoid.py / tanh.py /
// GELU.py with the -v flag (no Python changes required).
// -----------------------------------------------------------------------------
`timescale 1ns/1ps

module sigmoid_subenv_tb;

    // DUT I/O
    reg  [31:0] x;
    reg  [1:0]  opcode;
    wire [31:0] y;

    // Instantiate DUT
    sigmoid_subenv dut (
        .x(x),
        .opcode(opcode),
        .y(y)
    );

    // Error tracking (overall + per-function)
    integer error_count;
    integer test_count;
    integer sigmoid_errors, tanh_errors, gelu_errors;
    integer sigmoid_tests,  tanh_tests,  gelu_tests;

    // For calculations
    reg [31:0] expected;




    ////////////////////////////////////////////////////////////////////
    //   Never modify below this line except the included file names  //
    ////////////////////////////////////////////////////////////////////



    // Single shared check task — dispatches to the function currently
    // selected by `opcode` (set by the initial block before each `include).
    task check_result(input [31:0] x_in, input [31:0] exp_out);
    begin
        x        = x_in;
        expected = exp_out;
        #10;

        test_count = test_count + 1;
        case (opcode)
            2'b00: sigmoid_tests = sigmoid_tests + 1;
            2'b01: tanh_tests    = tanh_tests    + 1;
            2'b10: gelu_tests    = gelu_tests    + 1;
            default: ;
        endcase

        if (y !== expected) begin
            error_count = error_count + 1;
            case (opcode)
                2'b00: sigmoid_errors = sigmoid_errors + 1;
                2'b01: tanh_errors    = tanh_errors    + 1;
                2'b10: gelu_errors    = gelu_errors    + 1;
                default: ;
            endcase
            $display("[%0t ns] [op=%b] :: MISMATCH at x=0x%08h: y=0x%08h, expected=0x%08h",
                     $time, opcode, x_in, y, exp_out);
        end else begin
            $display("[%0t ns] [op=%b] :: PASS at x=0x%08h: y=0x%08h",
                     $time, opcode, x_in, y);
        end
    end
    endtask

    // Main test
    initial begin
        if ($test$plusargs("WAVE")) begin
            $dumpfile("sigmoid_subenv");       // no extension
            $dumpvars(0, sigmoid_subenv_tb);
        end

        error_count    = 0;
        test_count     = 0;
        sigmoid_errors = 0;
        tanh_errors    = 0;
        gelu_errors    = 0;
        sigmoid_tests  = 0;
        tanh_tests     = 0;
        gelu_tests     = 0;

        $display("===========================================");
        $display("sigmoid_subenv Testbench Starting");
        $display("===========================================");

        // ---- Sigmoid section (opcode = 2'b00) ----
        opcode = 2'b00;
        $display(">>> SIGMOID vectors <<<");
        `include "sigmoid_vectors.sv"
        `include "sigmoid_neg_vectors.sv"

        // ---- Tanh section (opcode = 2'b01) ----
        opcode = 2'b01;
        $display(">>> TANH vectors <<<");
        `include "tanh_vectors.sv"

        // ---- GELU section (opcode = 2'b10) ----
        opcode = 2'b10;
        $display(">>> GELU vectors <<<");
        `include "gelu_vectors.sv"

        $display("===========================================");
        $display("Per-function results:");
        $display("  Sigmoid : %0d/%0d passed", sigmoid_tests - sigmoid_errors, sigmoid_tests);
        $display("  Tanh    : %0d/%0d passed", tanh_tests    - tanh_errors,    tanh_tests);
        $display("  GELU    : %0d/%0d passed", gelu_tests    - gelu_errors,    gelu_tests);
        $display("-------------------------------------------");
        $display("Overall : %0d/%0d passed", test_count - error_count, test_count);
        if (error_count > 0)
            $display("FAILED with %0d errors", error_count);
        else
            $display("ALL TESTS PASSED");
        $display("===========================================");

        $finish;
    end

endmodule
